### ISSUE TITLE
Provide a .deb package?

### ISSUE THREAD

**Issue by NoNaMoe** [home-assistant/supervised-installer#95]
The script we have atm seems simple enough, why not package it in a .deb? It could install the required packages automatically and simplify the install for end users. 

Long term goal could be to package the binaries to distros official repositories... 
Imagine a full installation as easy as 'sudo apt install home-assistant'. 

With the rebrand i can see this type of install becoming the 2nd most typical route after imaging. (venv has already disappeared from official docs) 

Personally I've been eyeing up the HA supervised script/instructions for a while but don't fancy manually installing packages that may be orphaned, and downloading docker when its already present in my distro repo.

**Comment by pvizeli** [comment]
I don't want to maintain that. There is enough work for me and more comes, but this is not necessary. I let it open for everyone to provide a private deb for other people. 

One of the biggest problems would be that the docker-ce is not part of any official sources, and we relay on docker-ce. That means, more as a private .deb is anyway not possible.

I'm also not a big fan of the supervised-installer because that was initially just for developers. The supervisor takes control of the whole system and is not care of any other software or use case of this computer, which difficult if you want to use other stuff on the computer. In that case, you are better to use just the Home Assistant Core and not the Home Assistant as a full solution.
